name: ASP.NET Core CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Restore with dotnet
      run: dotnet restore
    - name: Build with dotnet
      run: dotnet build
    - name: Test with dotnet
      run: dotnet test
    - name: Publish with dotnet
      run: dotnet publish -c release
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: ./src/PartsUnlimitedWebsite/bin/Release/netcoreapp2.0/publish/
      
  prepare-environment:

    runs-on: ubuntu-latest

    steps:

    - uses: azure/actions/login@master

      with:

        creds: ${{ secrets.AzureCredentials }}
    - name: Create or Update Resource Group
      run: |
           az group create --name 'GitHubActionsRG' --location 'westus'
           az appservice plan create --resource-group GitHubActionsRG --name MyGHPlan --sku S1
           az webapp create --resource-group GitHubActionsRG --plan MyGHPlan --name MyGitHubactionsweb2210
